// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lumel.Domain.Entities;

public partial class DataRefreshLog
{
    public int Id { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Status { get; set; }

    public int RecordsProcessed { get; set; }

    public string ErrorMessage { get; set; }
}